### ISSUE TITLE
AutoScroll to bottom after adding item to list

### ISSUE THREAD

**Issue by ultrarunner** [mlabouardy/dialogflow-angular5#1]
It would be convenient if the list auto-scrolled to the bottom when adding a new item to the conversation so users do not have to scroll down manually. I think I can fix this one. I will submit a pull request shortly.

**Comment by mlabouardy** [comment]
thanks :) merged https://github.com/mlabouardy/dialogflow-angular5/commit/230bd9571188c3e0d077b7cc2551f7e46cff9f35

**Comment by Mohanbuggana** [comment]
**AutoScroll to bottom** is not working. Can you please check the code.
